def credit():
    print "                              !!!CREDITS!!!"
    print "_________________________________________________________________________________"
    print "|| Roll no.||         Name.       || Class.  ||  Work done                     ||"    
    print "---------------------------------------------------------------------------------"
    print "||   12    || Debabrata Mukherjee || XI 'A'  || Commandline version of 'Does   ||"
    print "||         ||                     ||         || it contain forbidden letters??'||"
    print "---------------------------------------------------------------------------------"
    print "||   15    ||    Dibyendu Das     || XI 'A'  || Commandline & Graphical version||"
    print "||         ||                     ||         || 'CREDITS',Debugging of opening ||"
    print "||         ||                     ||         ||  game window                   ||"
    print "---------------------------------------------------------------------------------"
    print "||   28    ||  Rajdeep Deogharia  || XI 'A'  || Commandline version of         ||"
    print "||         ||                     ||         || 'High / Low'                   ||"
    print "---------------------------------------------------------------------------------"
    print "||   39    ||    Souhardya Sen    || XI 'A'  || Commandline version of 'Cows   ||"
    print "||         ||                     ||         || 'N Bulls',PA Games Logo        ||"
    print "---------------------------------------------------------------------------------"
    print "||   46    ||   Subrata Sarkar    || XI 'A'  || Commandline & Graphical version||"
    print "||         ||                     ||         || 'Hangman', Graphical version of||"
    print "||         ||                     ||         ||  High/Low, Graphical version of||"
    print "||         ||                     ||         ||  'Cows 'N Bulls', Graphical    ||"
    print "||         ||                     ||         ||  version of 'Does it contain   ||"
    print "||         ||                     ||         ||  forbidden letters??',Sound in ||"
    print "||         ||                     ||         ||  Graphical version  ,Product   ||"
    print "||         ||                     ||         ||  Registration feature,Exception||"
    print "||         ||                     ||         ||  Handling,Debugging entire game||"
    print "_______________________________________________________________________________||"

